### ISSUE TITLE
When uploaded file is bigger than `upload_max_filesize` then ambiguous exception is thrown

### ISSUE THREAD

**Issue by chives** [fsi-open/files#58]
If uploaded file is bigger than `upload_max_filesize` then `SymfonyFileToWebFileTransformer` tries to check file's mime-type which throws exception with message `The "" file does not exist or is not readable.` We should try to change this behaviour in order to give better error message to the user and/or developer

**Comment by szymach** [comment]
The solution would be to create an empty file object with only the error code and whatever information is available in the `UploadedFile` object.

**Comment by szymach** [comment]
Solved by #60
